'use strict';const canvasSize=400,gridSize=11,snakeStartSpeed=25,snakeEndSpeed=8,cellSize=canvasSize/gridSize;let snakeSpeed=snakeStartSpeed,snakeArray=[],foodX=0,foodY=0,snakeArrayDirection="",timer=0;
function setup(){textSize(24);createCanvas(canvasSize,canvasSize+100);setNewFoodLocation(gridSize);snakeArray.push({x:Math.floor(gridSize/2),y:Math.floor(gridSize/2)})}
function draw(){background(255);fill("black");text("Score: "+snakeArray.length,10,canvasSize+90);text("use arrow keys to move",10,canvasSize+60);drawGrid();drawSnake();drawFood();checkCollision();moveSnake()}
function keyPressed(){keyCode===LEFT_ARROW&&"right"!==snakeArrayDirection?snakeArrayDirection="left":keyCode===RIGHT_ARROW&&"left"!==snakeArrayDirection?snakeArrayDirection="right":keyCode===UP_ARROW&&"down"!==snakeArrayDirection?snakeArrayDirection="up":keyCode===DOWN_ARROW&&"up"!==snakeArrayDirection&&(snakeArrayDirection="down")}
function drawGrid(){fill("white");for(let a=0;a<=gridSize;a++)for(let b=0;b<=gridSize;b++)rect(a*cellSize,b*cellSize,cellSize,cellSize)}
function drawSnake(){fill("black");for(let a=0;a<snakeArray.length;a++)rect(snakeArray[a].x*cellSize,snakeArray[a].y*cellSize,cellSize,cellSize)}
function drawFood(){fill("red");rect(foodX*cellSize,foodY*cellSize,cellSize,cellSize)}
function setNewFoodLocation(a){let b=[];for(let c=0;c<a;c++)for(let d=0;d<a;d++){let f=!0;for(let e=0;e<snakeArray.length;e++)snakeArray[e].x==c&&snakeArray[e].y==d&&(f=!1);f&&b.push({x:c,y:d})}a=Math.floor(random(0,b.length));foodX=b[a].x;foodY=b[a].y}
function checkCollision(){snakeArray[0].x==foodX&&snakeArray[0].y==foodY&&(setNewFoodLocation(gridSize),snakeArray.push({x:snakeArray[snakeArray.length-1].x,y:snakeArray[snakeArray.length-1].y}),--snakeSpeed,snakeSpeed<snakeEndSpeed&&(snakeSpeed=snakeEndSpeed))}
function moveSnake(){timer++;if(timer==snakeSpeed){timer=0;let a={x:snakeArray[0].x,y:snakeArray[0].y};"left"===snakeArrayDirection?a.x--:"right"===snakeArrayDirection?a.x++:"up"===snakeArrayDirection?a.y--:"down"===snakeArrayDirection&&a.y++;snakeArray.unshift(a);snakeArray.pop();for(let b=1;b<snakeArray.length;b++)snakeArray[0].x==snakeArray[b].x&&snakeArray[0].y==snakeArray[b].y&&resetGame();(0>a.x||a.x>gridSize-1||0>a.y||a.y>gridSize-1)&&resetGame()}}
function resetGame(){snakeArray=[];setNewFoodLocation(gridSize);snakeArray.push({x:Math.floor(gridSize/2),y:Math.floor(gridSize/2)});snakeSpeed=25;snakeArrayDirection=""};